### ISSUE TITLE
Converting authentication to React-Redux 

### ISSUE THREAD

**Issue by leonardolouie** [1601/gatsby-netlify-cms-sho#17]
## Feature request

**What is the expected behavior?**
Connecting react app to redux .. 

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**
https://drive.google.com/drive/u/1/folders/1ZfjAEBuItokGroouOlKKPHEy1E6LcOat

**Are you willing to work on this yourself?**
yes

**Comment by 1601** [comment]
#21 connecting the pull-request in this issue. 

Kindly attend to the pull-request bugs

cc: @leonardolouie
