### ISSUE TITLE
Create custom Login with AWS Cognito with shoco Branding

### ISSUE THREAD

**Issue by MiguelQXXV** [1601/gatsby-netlify-cms-sho#23]
## Feature request

**What is the expected behavior?**
add branding 

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by erangot** [comment]
![design 1](https://user-images.githubusercontent.com/30464172/60421514-95567780-9c1c-11e9-81d3-2b9a7fad8ee8.jpg)
![design 2](https://user-images.githubusercontent.com/30464172/60421516-95567780-9c1c-11e9-9dc5-9cb550c5359a.jpg)

@1601 Mock-ups for sho.co login page. Kindly suggest if changes are needed to be made. Thanks!

**Comment by erangot** [comment]
revised

![design 4](https://user-images.githubusercontent.com/30464172/60483689-2125dd80-9cc9-11e9-8709-77f8ac6cf58e.jpg)
![design 3](https://user-images.githubusercontent.com/30464172/60483690-2125dd80-9cc9-11e9-842c-c1eb769fdd38.jpg)

**Comment by 1601** [comment]
Released on release/0.1
