### ISSUE TITLE
Refactoring shoco 

### ISSUE THREAD

**Issue by leonardolouie** [1601/gatsby-netlify-cms-sho#27]
## Feature request

**What is the expected behavior?**
Removing  or to minimize all the duplicates files inside shoco to lower down the MAINTAINABILITY according to code climate 

**What is motivation or use case for adding/changing the behavior?**
![Uploading  #image.png…]()

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by leonardolouie** [comment]
@1601 this one the new issue for refactoring shoco

**Comment by leonardolouie** [comment]
https://github.com/1601/gatsby-netlify-cms-sho/commits/feature/refactoring-shoco 
branch for this issue

**Comment by leonardolouie** [comment]
![image](https://user-images.githubusercontent.com/29114998/59895857-c9f65200-9418-11e9-9528-67476e0e069a.png)

**Comment by 1601** [comment]
### Sub Issues:
- [ ] #93
- [ ] #90
- [ ] #86 
- [ ] #85
- [ ]  #84 
- [ ]  #82 
- [ ] #83
- [ ] #81 
- [ ] #88
- [ ] #89  
- [ ] #80
- [ ] #79
- [ ] #70

**Comment by 1601** [comment]
Kindly add the linter for VSCode on the rea.me
